worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

grpc-endpoint: "ai-service:8090"
dbconnection: 'postgresql://testsuite@localhost:15433/noteluoto_db_1'
