components_manager:
    task_processors:                  
        main-task-processor:        
            worker_threads: $worker-threads        

        fs-task-processor:            
            worker_threads: $worker-fs-threads

        grpc-blocking-task-processor:
            worker_threads: $worker-grpc-threads
            thread_name: grpc-worker

    default_task_processor: main-task-processor

    components:                       
        server:
            listener:                 
                port: $server-port            
                task_processor: main-task-processor    
        custom-handler-pipeline-builder:
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'        # Куда записываются логи
                    level: $logger-level
                    overflow_behavior: discard  # Удаление логов, если система слишком занята, чтобы их записать.

        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        grpc-client-common:
            blocking-task-processor: grpc-blocking-task-processor

        grpc-client-factory:
            channel-args: {}


        # grpc-client-logging:
        grpc-client-deadline-propagation: 
            enabled: true
        # grpc-client-middleware-testsuite:

        # grpc-client-middleware-testsuite:
        note-sync-client: 
            endpoint: $grpc-endpoint

        langchain-client: 
            endpoint: $grpc-endpoint

        tag-recommender-client:
            endpoint: $grpc-endpoint

        http-client:
            load-enabled: $is-testing
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-api-register:
            path: /auth/register
            method: POST,OPTIONS
            middlewares:
                pipeline-builder: custom-handler-pipeline-builder
                cors-middleware:

            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match
            
        handler-post-api-login:
            path: /auth/login
            method: POST,OPTIONS
            middlewares:
                pipeline-builder: custom-handler-pipeline-builder
                cors-middleware:


            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-history:
            path: /history
            method: GET,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-suggest-tags:
            path: /suggest/tags/{note_id}
            method: POST,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-suggest-queries:
            path: /suggest/queries
            method: GET,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-ai-answer:
            path: /ai/answer
            method: POST,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        # Эндпоинты для работы с заметками
        handler-get-all-notes:
            path: /notes
            method: GET,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-note:
            path: /notes
            method: POST

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match
            
        handler-get-note:
            path: /notes/{note_id}
            method: GET,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-patch-note:
            path: /notes/{note_id}
            method: PATCH

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-delete-note:
            path: /notes/{note_id}
            method: DELETE

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match
            
        # Эндпоинты для работы с тегами
        handler-post-tags-create:
            path: /tags/create
            method: POST,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-tags-all:
            path: /tags/all
            method: GET,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-tags-note:
            path: /tags/{note_id}
            method: GET,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-tags-note-tag:
            path: /tags/{note_id}/{tag_id}
            method: POST,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-delete-tags-note-tag:
            path: /tags/{note_id}/{tag_id}
            method: DELETE

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        # Эндпоинты для работы с чеклистами
        handler-post-checklist-note:
            path: /checklist/{note_id}
            method: POST,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-checklist:
            path: /checklist/{checklist_id}
            method: GET

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-delete-checklist:
            path: /checklist/{checklist_id}
            method: DELETE

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-patch-checklist:
            path: /checklist/{checklist_id}
            method: PATCH


            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match


        # Эндпоинты для работы с пунктами чеклистов
        handler-post-checklist-item:
            path: /checklist/{checklist_id}/item
            method: POST,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-patch-checklist-item:
            path: /checklist/item/{item_id}
            method: PATCH,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-delete-checklist-item:
            path: /checklist/item/{item_id}
            method: DELETE

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        # Эндпоинты для работы с вложениями 
        handler-post-attachment-note:
            path: /attachment/{note_id}
            method: POST,OPTIONS

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-attachment:
            path: /attachment/{attachment_id}
            method: GET

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-delete-attachment:
            path: /attachment/{attachment_id}
            method: DELETE

            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match
            
        # Регистрация базы данных
        postgres-db-1:
            dbconnection: $dbconnection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        secdist: {}
        default-secdist-provider:
            config: 'configs/jwt_config.json'
            
        dns-client:
            fs-task-processor: fs-task-processor
